#!/usr/bin/env bash
# A Bash scriptt that transfers a file from our client to a server

if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed"
else
	# assign parameters to variables
	PATH_TO_FILE="$1"
	IP="$2"
	USERNAME="$3"
	PATH_TO_SSH_KEY="$4"

	scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
fi
