#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
#  it must return a page that contains the string Hello World!

sudo apt-get upgrade
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
		
	root /var/www/html;
	index index.html;
		
	server_name _;
	location / {
		try_files $uri $uri/ =404;
	}
		
	location /hello {
		return 200 "Hello World!";
	}
" | sudo tee /etc/nginx/sites-available/default

sudo nginx -t
