#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R ubuntu /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\
        \n\troot \/var\/www\/html;\n\tindex index.html;\
        \n\tlocation \/redirect_me{\
        \n\treturn 301 https:\/\/github.com\/theChosenDevop;\
        \n}"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo nginx -t
