#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# Nginx server have a custom 404 page that contains the string Ceci n'est pas une

sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R ubuntu /var/www

# 301 redirection
echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/theChosenDevop permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

string_to_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_to_replace/" /etc/nginx/sites-enabled/default

sudo service nginx reload
sudo nginx -t
