#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get upgrade
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i 's/# listen 80;/listen 80;/g' /etc/nginx/sites-available/default
sudo sed -i 's/# listen \[::\]:80;/listen \[::\]:80;/g' /etc/nginx/sites-available/default
sudo sed -i 's/# server_name _;/server_name _;/g' /etc/nginx/sites-available/default
sudo sed -i 's/# root \/var\/www\/html;/root \/var\/wwww\/html;/g' /etc/nginx/sites-available/default
sudo sed -i 's/# index index.html;/index index.html;/g' /etc/nginx/sites-available/default
sudo sed -i 's/# location \/ {/location \/ {\n       try_files $uri $uri\/ =404;\n    }/g' /etc/nginx/sites-available/default
sudo sed -i 's/# location \/hello {/location \/hello {\n       return 200 \"Hello World!\";\n    }/g' /etc/nginx/sites-available/default

sudo sed -i 's/# listen 80;/listen 80;/g' /etc/nginx/sites-available/redirect_me
sudo sed -i 's/# listen \[::\]:80;/listen \[::\]:80;/g' /etc/nginx/sites-available/redirect_me
sudo sed -i 's/# server_name _;/server_name _;/g' /etc/nginx/sites-available/redirect_me
sudo sed -i 's/# location \/redirect_me {/location \/redirect_me {\n       return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n   }/g' /etc/nginx/sites-available/redirect_me

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled
sudo service nginx restart
sudo nginx -t
