#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains
# a custom header (on web-01 and web-02

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Back default configuration file
#sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

# configure Nginx
sudo sed -i 's/# server_tokens off;/server_tokens off;/' /etc/nginx/nginx.conf
sudo sed -i '/http {/a \        more_set_headers "X-Served-By: $HOSTNAME";' /etc/nginx/nginx.conf

sudo systemctl restart nginx
