#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains
# a custom header (on web-01 and web-02)

# Install Nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

echo "server{
	listen 80;
	listen [::]:80;

	server_name _;

	error_page 404 /custom_404.html;
	add_header X-Served-By $HOSTNAME;

	location / {
		root /var/www/html;
		index index.html;
	}

	location /redirect_me {
		return 301 https://github.com/theChosenDevop;
	}
	
	location /404 {
		root /var/www/html;
		internal;
	}
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
sudo nginx -t
