#!/usr/bin/env bash
#install HAproxy

apt-get update
apt-get install -y haproxy

echo "ENABLED=1" | tee -a /etc/default/haproxy
echo "CONFIG=/etc/haproxy/haproxy.cfg" | tee -a /etc/default/haproxy

echo "
frontend front
  bind *:80
  default_backend back

backend web-backend
  balance roundrobin
  server 240049-web-01 35.174.207.6:80 check
  server 240049-web-02 52.3.254.148:80 check" | tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
