#!/usr/bin/env bash
#install HAproxy

sudo apt-get -y update
sudo apt-get install --no-install-recommends software-properies-common
sudoadd-apt-respository ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo "CONFIG=/etc/haproxy/haproxy.cfg" | sudo tee -a /etc/default/haproxy

echo "
frontend front
  bind *:80
  default_backend back

backend web-backend
  balance roundrobin
  server 240049-web-01 35.174.207.6:80 check
  server 240049-web-02 52.3.254.148:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudu service haproxy restart
