#!/usr/bin/env bash
#install HAproxy

sudo apt-get -y update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-respository ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo "CONFIG=/etc/haproxy/haproxy.cfg" | sudo tee -a /etc/default/haproxy

echo "
frontend front
  bind *:80
  default_backend web-backend

backend web-backend
  balance roundrobin
  server 240049-web-01 3.84.255.185:80 check  server 240049-web-02 54.157.182.6:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
