#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal

pid_file="/var/run/myscript.id"

remove_file()
{
	rm "$pid_file"
	exit
}

echo "$$" > "$pid_file"
trap 'echo "I hate the kill command" && remove_file' TERM
trap 'echo "Y U no love me?!"' INT

while :; do
	echo "To infinity and beyond"
	sleep 2
done
