#!/usr/bin/env bash
# creates and deletes directories and file

remove_file()
{
	rm  /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while :; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo"I hate the kill command"' TERM
	trap 'echo"Y U no love me?!"' INT
	trap 'remove_file' QUIT
done
