#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal

remove_file()
{
	rm /var/run/myscript.id
	exit
}

echo "$$" > /var/run/myscript.pid

while :; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && remove_file' TERM
	trap 'remove_file' SIGQUIT
done
