#!/usr/bin/env bash
# Bash script displays the content of the file /etc/passwd
# displays username
# display user id
# displays Home directory path for the user

file_path="/etc/passwd"

while IFS=: read -r username _ userid _ _ home _
do
	echo "$username:$userid:$home"
done < "$file_path"
