#!/usr/bin/env bash
#Bash Script that loops from 1 - 10
#Displays bad luck for the 4th loop iteration
#Displays good luck for the 8th loop iteration
#Displays Best School for the other iterations

i=1

while [ $i -ne 11 ]
do
	if [ $i -eq 4 ]; then
	echo "bad luck"
	elif [ $i -eq 8 ]; then
	echo "good luck"
	else
	echo "Best School"
	fi
	((i++))
done
