#!/usr/bin/env bash
#Bash Script that displays number 1 to 20
#displays superstitious words below
#displays 4 and then back luck from China for the 4th loop iteration
#displays 9 and then bad luck rom Japan for the 9th loop iteration
#display 17 and then bad luck from italy for the 17th loop iteration

i=1

while [ $i -lt 21 ]
do
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((i++))
done
