#!/usr/bin/env bash
# nginx must be running as nginx user
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# nginx must be listening on all active IPs on port 8080
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
