#!/usr/bin/env bash
# Ensure that Nginx runs as the nginx user and listens on port 8080 in 7 lines
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
sudo service nginx restart
