#!/usr/bin/env bash
# Ensure that Nginx runs as the nginx user and listens on port 8080 in 7 lines
chmosd 204 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
pkill -f apache2
sudo -u nginx service nginx start
